/*Generated by WaveMaker Studio*/


package com.web_19thjan.test13uu798.service;


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomProcedure;
import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class Test13uu798ProcedureExecutorServiceImpl implements Test13uu798ProcedureExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(Test13uu798ProcedureExecutorServiceImpl.class);

	@Autowired
	@Qualifier("Test13uu798WMProcedureExecutor")
	private WMProcedureExecutor procedureExecutor;


	@Transactional(value = "Test13uu798TransactionManager")
	@Override
	public List<Object> executeWMCustomProcedure(CustomProcedure procedure) {
	    return procedureExecutor.executeCustomProcedure(procedure);
	}


}

